// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Infrastructure.Data;

#nullable disable

namespace Project.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250221142613_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.Domain.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("ShowTimeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("ShowTimeId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Project.Domain.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PosterUrl = "https://movie.com/Lalaland.jpg",
                            Title = "La La Land"
                        },
                        new
                        {
                            Id = 2,
                            PosterUrl = "https://movie.com/Inception.jpg",
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 3,
                            PosterUrl = "https://movie.com/Titanic.jpg",
                            Title = "Titanic"
                        });
                });

            modelBuilder.Entity("Project.Domain.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Orange Room"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Blue Room"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Red Room"
                        });
                });

            modelBuilder.Entity("Project.Domain.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 1,
                            Row = 1
                        },
                        new
                        {
                            Id = 2,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 1,
                            Row = 1
                        },
                        new
                        {
                            Id = 3,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 1,
                            Row = 1
                        },
                        new
                        {
                            Id = 4,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 1,
                            Row = 1
                        },
                        new
                        {
                            Id = 5,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 1,
                            Row = 1
                        },
                        new
                        {
                            Id = 6,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 1,
                            Row = 1
                        },
                        new
                        {
                            Id = 7,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 1,
                            Row = 1
                        },
                        new
                        {
                            Id = 8,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 1,
                            Row = 1
                        },
                        new
                        {
                            Id = 9,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 1,
                            Row = 2
                        },
                        new
                        {
                            Id = 10,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 1,
                            Row = 2
                        },
                        new
                        {
                            Id = 11,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 1,
                            Row = 2
                        },
                        new
                        {
                            Id = 12,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 1,
                            Row = 2
                        },
                        new
                        {
                            Id = 13,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 1,
                            Row = 2
                        },
                        new
                        {
                            Id = 14,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 1,
                            Row = 2
                        },
                        new
                        {
                            Id = 15,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 1,
                            Row = 2
                        },
                        new
                        {
                            Id = 16,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 1,
                            Row = 2
                        },
                        new
                        {
                            Id = 17,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 1,
                            Row = 3
                        },
                        new
                        {
                            Id = 18,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 1,
                            Row = 3
                        },
                        new
                        {
                            Id = 19,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 1,
                            Row = 3
                        },
                        new
                        {
                            Id = 20,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 1,
                            Row = 3
                        },
                        new
                        {
                            Id = 21,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 1,
                            Row = 3
                        },
                        new
                        {
                            Id = 22,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 1,
                            Row = 3
                        },
                        new
                        {
                            Id = 23,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 1,
                            Row = 3
                        },
                        new
                        {
                            Id = 24,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 1,
                            Row = 3
                        },
                        new
                        {
                            Id = 25,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 1,
                            Row = 4
                        },
                        new
                        {
                            Id = 26,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 1,
                            Row = 4
                        },
                        new
                        {
                            Id = 27,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 1,
                            Row = 4
                        },
                        new
                        {
                            Id = 28,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 1,
                            Row = 4
                        },
                        new
                        {
                            Id = 29,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 1,
                            Row = 4
                        },
                        new
                        {
                            Id = 30,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 1,
                            Row = 4
                        },
                        new
                        {
                            Id = 31,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 1,
                            Row = 4
                        },
                        new
                        {
                            Id = 32,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 1,
                            Row = 4
                        },
                        new
                        {
                            Id = 33,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 1,
                            Row = 5
                        },
                        new
                        {
                            Id = 34,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 1,
                            Row = 5
                        },
                        new
                        {
                            Id = 35,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 1,
                            Row = 5
                        },
                        new
                        {
                            Id = 36,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 1,
                            Row = 5
                        },
                        new
                        {
                            Id = 37,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 1,
                            Row = 5
                        },
                        new
                        {
                            Id = 38,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 1,
                            Row = 5
                        },
                        new
                        {
                            Id = 39,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 1,
                            Row = 5
                        },
                        new
                        {
                            Id = 40,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 1,
                            Row = 5
                        },
                        new
                        {
                            Id = 41,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 1,
                            Row = 6
                        },
                        new
                        {
                            Id = 42,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 1,
                            Row = 6
                        },
                        new
                        {
                            Id = 43,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 1,
                            Row = 6
                        },
                        new
                        {
                            Id = 44,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 1,
                            Row = 6
                        },
                        new
                        {
                            Id = 45,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 1,
                            Row = 6
                        },
                        new
                        {
                            Id = 46,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 1,
                            Row = 6
                        },
                        new
                        {
                            Id = 47,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 1,
                            Row = 6
                        },
                        new
                        {
                            Id = 48,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 1,
                            Row = 6
                        },
                        new
                        {
                            Id = 49,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 1,
                            Row = 7
                        },
                        new
                        {
                            Id = 50,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 1,
                            Row = 7
                        },
                        new
                        {
                            Id = 51,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 1,
                            Row = 7
                        },
                        new
                        {
                            Id = 52,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 1,
                            Row = 7
                        },
                        new
                        {
                            Id = 53,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 1,
                            Row = 7
                        },
                        new
                        {
                            Id = 54,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 1,
                            Row = 7
                        },
                        new
                        {
                            Id = 55,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 1,
                            Row = 7
                        },
                        new
                        {
                            Id = 56,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 1,
                            Row = 7
                        },
                        new
                        {
                            Id = 57,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 1,
                            Row = 8
                        },
                        new
                        {
                            Id = 58,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 1,
                            Row = 8
                        },
                        new
                        {
                            Id = 59,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 1,
                            Row = 8
                        },
                        new
                        {
                            Id = 60,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 1,
                            Row = 8
                        },
                        new
                        {
                            Id = 61,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 1,
                            Row = 8
                        },
                        new
                        {
                            Id = 62,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 1,
                            Row = 8
                        },
                        new
                        {
                            Id = 63,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 1,
                            Row = 8
                        },
                        new
                        {
                            Id = 64,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 1,
                            Row = 8
                        },
                        new
                        {
                            Id = 65,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 1,
                            Row = 9
                        },
                        new
                        {
                            Id = 66,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 1,
                            Row = 9
                        },
                        new
                        {
                            Id = 67,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 1,
                            Row = 9
                        },
                        new
                        {
                            Id = 68,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 1,
                            Row = 9
                        },
                        new
                        {
                            Id = 69,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 1,
                            Row = 9
                        },
                        new
                        {
                            Id = 70,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 1,
                            Row = 9
                        },
                        new
                        {
                            Id = 71,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 1,
                            Row = 9
                        },
                        new
                        {
                            Id = 72,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 1,
                            Row = 9
                        },
                        new
                        {
                            Id = 73,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 1,
                            Row = 10
                        },
                        new
                        {
                            Id = 74,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 1,
                            Row = 10
                        },
                        new
                        {
                            Id = 75,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 1,
                            Row = 10
                        },
                        new
                        {
                            Id = 76,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 1,
                            Row = 10
                        },
                        new
                        {
                            Id = 77,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 1,
                            Row = 10
                        },
                        new
                        {
                            Id = 78,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 1,
                            Row = 10
                        },
                        new
                        {
                            Id = 79,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 1,
                            Row = 10
                        },
                        new
                        {
                            Id = 80,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 1,
                            Row = 10
                        },
                        new
                        {
                            Id = 81,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 2,
                            Row = 1
                        },
                        new
                        {
                            Id = 82,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 2,
                            Row = 1
                        },
                        new
                        {
                            Id = 83,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 2,
                            Row = 1
                        },
                        new
                        {
                            Id = 84,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 2,
                            Row = 1
                        },
                        new
                        {
                            Id = 85,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 2,
                            Row = 1
                        },
                        new
                        {
                            Id = 86,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 2,
                            Row = 1
                        },
                        new
                        {
                            Id = 87,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 2,
                            Row = 1
                        },
                        new
                        {
                            Id = 88,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 2,
                            Row = 1
                        },
                        new
                        {
                            Id = 89,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 2,
                            Row = 2
                        },
                        new
                        {
                            Id = 90,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 2,
                            Row = 2
                        },
                        new
                        {
                            Id = 91,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 2,
                            Row = 2
                        },
                        new
                        {
                            Id = 92,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 2,
                            Row = 2
                        },
                        new
                        {
                            Id = 93,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 2,
                            Row = 2
                        },
                        new
                        {
                            Id = 94,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 2,
                            Row = 2
                        },
                        new
                        {
                            Id = 95,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 2,
                            Row = 2
                        },
                        new
                        {
                            Id = 96,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 2,
                            Row = 2
                        },
                        new
                        {
                            Id = 97,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 2,
                            Row = 3
                        },
                        new
                        {
                            Id = 98,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 2,
                            Row = 3
                        },
                        new
                        {
                            Id = 99,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 2,
                            Row = 3
                        },
                        new
                        {
                            Id = 100,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 2,
                            Row = 3
                        },
                        new
                        {
                            Id = 101,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 2,
                            Row = 3
                        },
                        new
                        {
                            Id = 102,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 2,
                            Row = 3
                        },
                        new
                        {
                            Id = 103,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 2,
                            Row = 3
                        },
                        new
                        {
                            Id = 104,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 2,
                            Row = 3
                        },
                        new
                        {
                            Id = 105,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 2,
                            Row = 4
                        },
                        new
                        {
                            Id = 106,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 2,
                            Row = 4
                        },
                        new
                        {
                            Id = 107,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 2,
                            Row = 4
                        },
                        new
                        {
                            Id = 108,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 2,
                            Row = 4
                        },
                        new
                        {
                            Id = 109,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 2,
                            Row = 4
                        },
                        new
                        {
                            Id = 110,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 2,
                            Row = 4
                        },
                        new
                        {
                            Id = 111,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 2,
                            Row = 4
                        },
                        new
                        {
                            Id = 112,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 2,
                            Row = 4
                        },
                        new
                        {
                            Id = 113,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 2,
                            Row = 5
                        },
                        new
                        {
                            Id = 114,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 2,
                            Row = 5
                        },
                        new
                        {
                            Id = 115,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 2,
                            Row = 5
                        },
                        new
                        {
                            Id = 116,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 2,
                            Row = 5
                        },
                        new
                        {
                            Id = 117,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 2,
                            Row = 5
                        },
                        new
                        {
                            Id = 118,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 2,
                            Row = 5
                        },
                        new
                        {
                            Id = 119,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 2,
                            Row = 5
                        },
                        new
                        {
                            Id = 120,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 2,
                            Row = 5
                        },
                        new
                        {
                            Id = 121,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 2,
                            Row = 6
                        },
                        new
                        {
                            Id = 122,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 2,
                            Row = 6
                        },
                        new
                        {
                            Id = 123,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 2,
                            Row = 6
                        },
                        new
                        {
                            Id = 124,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 2,
                            Row = 6
                        },
                        new
                        {
                            Id = 125,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 2,
                            Row = 6
                        },
                        new
                        {
                            Id = 126,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 2,
                            Row = 6
                        },
                        new
                        {
                            Id = 127,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 2,
                            Row = 6
                        },
                        new
                        {
                            Id = 128,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 2,
                            Row = 6
                        },
                        new
                        {
                            Id = 129,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 2,
                            Row = 7
                        },
                        new
                        {
                            Id = 130,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 2,
                            Row = 7
                        },
                        new
                        {
                            Id = 131,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 2,
                            Row = 7
                        },
                        new
                        {
                            Id = 132,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 2,
                            Row = 7
                        },
                        new
                        {
                            Id = 133,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 2,
                            Row = 7
                        },
                        new
                        {
                            Id = 134,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 2,
                            Row = 7
                        },
                        new
                        {
                            Id = 135,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 2,
                            Row = 7
                        },
                        new
                        {
                            Id = 136,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 2,
                            Row = 7
                        },
                        new
                        {
                            Id = 137,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 2,
                            Row = 8
                        },
                        new
                        {
                            Id = 138,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 2,
                            Row = 8
                        },
                        new
                        {
                            Id = 139,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 2,
                            Row = 8
                        },
                        new
                        {
                            Id = 140,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 2,
                            Row = 8
                        },
                        new
                        {
                            Id = 141,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 2,
                            Row = 8
                        },
                        new
                        {
                            Id = 142,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 2,
                            Row = 8
                        },
                        new
                        {
                            Id = 143,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 2,
                            Row = 8
                        },
                        new
                        {
                            Id = 144,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 2,
                            Row = 8
                        },
                        new
                        {
                            Id = 145,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 2,
                            Row = 9
                        },
                        new
                        {
                            Id = 146,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 2,
                            Row = 9
                        },
                        new
                        {
                            Id = 147,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 2,
                            Row = 9
                        },
                        new
                        {
                            Id = 148,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 2,
                            Row = 9
                        },
                        new
                        {
                            Id = 149,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 2,
                            Row = 9
                        },
                        new
                        {
                            Id = 150,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 2,
                            Row = 9
                        },
                        new
                        {
                            Id = 151,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 2,
                            Row = 9
                        },
                        new
                        {
                            Id = 152,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 2,
                            Row = 9
                        },
                        new
                        {
                            Id = 153,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 2,
                            Row = 10
                        },
                        new
                        {
                            Id = 154,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 2,
                            Row = 10
                        },
                        new
                        {
                            Id = 155,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 2,
                            Row = 10
                        },
                        new
                        {
                            Id = 156,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 2,
                            Row = 10
                        },
                        new
                        {
                            Id = 157,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 2,
                            Row = 10
                        },
                        new
                        {
                            Id = 158,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 2,
                            Row = 10
                        },
                        new
                        {
                            Id = 159,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 2,
                            Row = 10
                        },
                        new
                        {
                            Id = 160,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 2,
                            Row = 10
                        },
                        new
                        {
                            Id = 161,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 3,
                            Row = 1
                        },
                        new
                        {
                            Id = 162,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 3,
                            Row = 1
                        },
                        new
                        {
                            Id = 163,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 3,
                            Row = 1
                        },
                        new
                        {
                            Id = 164,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 3,
                            Row = 1
                        },
                        new
                        {
                            Id = 165,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 3,
                            Row = 1
                        },
                        new
                        {
                            Id = 166,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 3,
                            Row = 1
                        },
                        new
                        {
                            Id = 167,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 3,
                            Row = 1
                        },
                        new
                        {
                            Id = 168,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 3,
                            Row = 1
                        },
                        new
                        {
                            Id = 169,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 3,
                            Row = 2
                        },
                        new
                        {
                            Id = 170,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 3,
                            Row = 2
                        },
                        new
                        {
                            Id = 171,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 3,
                            Row = 2
                        },
                        new
                        {
                            Id = 172,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 3,
                            Row = 2
                        },
                        new
                        {
                            Id = 173,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 3,
                            Row = 2
                        },
                        new
                        {
                            Id = 174,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 3,
                            Row = 2
                        },
                        new
                        {
                            Id = 175,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 3,
                            Row = 2
                        },
                        new
                        {
                            Id = 176,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 3,
                            Row = 2
                        },
                        new
                        {
                            Id = 177,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 3,
                            Row = 3
                        },
                        new
                        {
                            Id = 178,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 3,
                            Row = 3
                        },
                        new
                        {
                            Id = 179,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 3,
                            Row = 3
                        },
                        new
                        {
                            Id = 180,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 3,
                            Row = 3
                        },
                        new
                        {
                            Id = 181,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 3,
                            Row = 3
                        },
                        new
                        {
                            Id = 182,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 3,
                            Row = 3
                        },
                        new
                        {
                            Id = 183,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 3,
                            Row = 3
                        },
                        new
                        {
                            Id = 184,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 3,
                            Row = 3
                        },
                        new
                        {
                            Id = 185,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 3,
                            Row = 4
                        },
                        new
                        {
                            Id = 186,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 3,
                            Row = 4
                        },
                        new
                        {
                            Id = 187,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 3,
                            Row = 4
                        },
                        new
                        {
                            Id = 188,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 3,
                            Row = 4
                        },
                        new
                        {
                            Id = 189,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 3,
                            Row = 4
                        },
                        new
                        {
                            Id = 190,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 3,
                            Row = 4
                        },
                        new
                        {
                            Id = 191,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 3,
                            Row = 4
                        },
                        new
                        {
                            Id = 192,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 3,
                            Row = 4
                        },
                        new
                        {
                            Id = 193,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 3,
                            Row = 5
                        },
                        new
                        {
                            Id = 194,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 3,
                            Row = 5
                        },
                        new
                        {
                            Id = 195,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 3,
                            Row = 5
                        },
                        new
                        {
                            Id = 196,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 3,
                            Row = 5
                        },
                        new
                        {
                            Id = 197,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 3,
                            Row = 5
                        },
                        new
                        {
                            Id = 198,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 3,
                            Row = 5
                        },
                        new
                        {
                            Id = 199,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 3,
                            Row = 5
                        },
                        new
                        {
                            Id = 200,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 3,
                            Row = 5
                        },
                        new
                        {
                            Id = 201,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 3,
                            Row = 6
                        },
                        new
                        {
                            Id = 202,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 3,
                            Row = 6
                        },
                        new
                        {
                            Id = 203,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 3,
                            Row = 6
                        },
                        new
                        {
                            Id = 204,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 3,
                            Row = 6
                        },
                        new
                        {
                            Id = 205,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 3,
                            Row = 6
                        },
                        new
                        {
                            Id = 206,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 3,
                            Row = 6
                        },
                        new
                        {
                            Id = 207,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 3,
                            Row = 6
                        },
                        new
                        {
                            Id = 208,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 3,
                            Row = 6
                        },
                        new
                        {
                            Id = 209,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 3,
                            Row = 7
                        },
                        new
                        {
                            Id = 210,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 3,
                            Row = 7
                        },
                        new
                        {
                            Id = 211,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 3,
                            Row = 7
                        },
                        new
                        {
                            Id = 212,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 3,
                            Row = 7
                        },
                        new
                        {
                            Id = 213,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 3,
                            Row = 7
                        },
                        new
                        {
                            Id = 214,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 3,
                            Row = 7
                        },
                        new
                        {
                            Id = 215,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 3,
                            Row = 7
                        },
                        new
                        {
                            Id = 216,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 3,
                            Row = 7
                        },
                        new
                        {
                            Id = 217,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 3,
                            Row = 8
                        },
                        new
                        {
                            Id = 218,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 3,
                            Row = 8
                        },
                        new
                        {
                            Id = 219,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 3,
                            Row = 8
                        },
                        new
                        {
                            Id = 220,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 3,
                            Row = 8
                        },
                        new
                        {
                            Id = 221,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 3,
                            Row = 8
                        },
                        new
                        {
                            Id = 222,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 3,
                            Row = 8
                        },
                        new
                        {
                            Id = 223,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 3,
                            Row = 8
                        },
                        new
                        {
                            Id = 224,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 3,
                            Row = 8
                        },
                        new
                        {
                            Id = 225,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 3,
                            Row = 9
                        },
                        new
                        {
                            Id = 226,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 3,
                            Row = 9
                        },
                        new
                        {
                            Id = 227,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 3,
                            Row = 9
                        },
                        new
                        {
                            Id = 228,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 3,
                            Row = 9
                        },
                        new
                        {
                            Id = 229,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 3,
                            Row = 9
                        },
                        new
                        {
                            Id = 230,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 3,
                            Row = 9
                        },
                        new
                        {
                            Id = 231,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 3,
                            Row = 9
                        },
                        new
                        {
                            Id = 232,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 3,
                            Row = 9
                        },
                        new
                        {
                            Id = 233,
                            IsBooked = false,
                            Number = 1,
                            RoomId = 3,
                            Row = 10
                        },
                        new
                        {
                            Id = 234,
                            IsBooked = false,
                            Number = 2,
                            RoomId = 3,
                            Row = 10
                        },
                        new
                        {
                            Id = 235,
                            IsBooked = false,
                            Number = 3,
                            RoomId = 3,
                            Row = 10
                        },
                        new
                        {
                            Id = 236,
                            IsBooked = false,
                            Number = 4,
                            RoomId = 3,
                            Row = 10
                        },
                        new
                        {
                            Id = 237,
                            IsBooked = false,
                            Number = 5,
                            RoomId = 3,
                            Row = 10
                        },
                        new
                        {
                            Id = 238,
                            IsBooked = false,
                            Number = 6,
                            RoomId = 3,
                            Row = 10
                        },
                        new
                        {
                            Id = 239,
                            IsBooked = false,
                            Number = 7,
                            RoomId = 3,
                            Row = 10
                        },
                        new
                        {
                            Id = 240,
                            IsBooked = false,
                            Number = 8,
                            RoomId = 3,
                            Row = 10
                        });
                });

            modelBuilder.Entity("Project.Domain.Models.ShowTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("ShowTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2025, 2, 21, 18, 26, 12, 841, DateTimeKind.Utc).AddTicks(2976),
                            MovieId = 1,
                            RoomId = 1,
                            StartTime = new DateTime(2025, 2, 21, 16, 26, 12, 841, DateTimeKind.Utc).AddTicks(2971)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(2025, 2, 21, 19, 26, 12, 841, DateTimeKind.Utc).AddTicks(2979),
                            MovieId = 2,
                            RoomId = 2,
                            StartTime = new DateTime(2025, 2, 21, 17, 26, 12, 841, DateTimeKind.Utc).AddTicks(2978)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new DateTime(2025, 2, 21, 20, 26, 12, 841, DateTimeKind.Utc).AddTicks(2980),
                            MovieId = 3,
                            RoomId = 3,
                            StartTime = new DateTime(2025, 2, 21, 18, 26, 12, 841, DateTimeKind.Utc).AddTicks(2980)
                        });
                });

            modelBuilder.Entity("Project.Domain.Models.Booking", b =>
                {
                    b.HasOne("Project.Domain.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Models.ShowTime", "ShowTime")
                        .WithMany()
                        .HasForeignKey("ShowTimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("ShowTime");
                });

            modelBuilder.Entity("Project.Domain.Models.Seat", b =>
                {
                    b.HasOne("Project.Domain.Models.Room", "Room")
                        .WithMany("Seats")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Project.Domain.Models.ShowTime", b =>
                {
                    b.HasOne("Project.Domain.Models.Movie", "Movie")
                        .WithMany("ShowTimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Models.Room", "Room")
                        .WithMany("ShowTimes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Project.Domain.Models.Movie", b =>
                {
                    b.Navigation("ShowTimes");
                });

            modelBuilder.Entity("Project.Domain.Models.Room", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("ShowTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
